import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../data/repositories.dart';
import '../../models/student_report_models.dart';
import '../../theme/colors.dart';
import '../../theme/text_styles.dart';
import '../../widgets/shared/bands.dart';
import '../../widgets/shared/buttons.dart';
import '../../widgets/shared/misc.dart';
import '../../widgets/shared/page_scaffold.dart';

/// The individual student report, generated by the real agent pipeline
/// (`report.for_student()` in app/report.py) and served as JSON by
/// `GET /api/report/{student_id}` (app/report_api.py).
///
/// Mirrors the information architecture of the web app's `/report/{sid}`
/// HTML page: the score, the agent's headline and prose, the by-topic table,
/// the next step — plus the same two provenance signals that page shows,
/// in plain language rather than jargon:
///
///   fromCache   "Showing the report from when you finished the quiz" vs
///               freshly generated, with a way to regenerate it.
///   unverified  "This wording has not been double-checked yet" — the
///               numbers behind it are still accurate.
class StudentReportScreen extends StatefulWidget {
  const StudentReportScreen({super.key, required this.studentId});

  final String studentId;

  @override
  State<StudentReportScreen> createState() => _StudentReportScreenState();
}

class _StudentReportScreenState extends State<StudentReportScreen> {
  late Future<StudentReport> _future;
  bool _regenerating = false;

  @override
  void initState() {
    super.initState();
    _future = _load();
  }

  Future<StudentReport> _load({bool force = false}) =>
      context.read<StudentReportRepository>().report(
        widget.studentId,
        force: force,
      );

  void _reload() => setState(() => _future = _load());

  Future<void> _regenerate() async {
    setState(() => _regenerating = true);
    final next = _load(force: true);
    setState(() {
      _future = next;
    });
    await next.whenComplete(() {
      if (mounted) setState(() => _regenerating = false);
    });
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<StudentReport>(
      future: _future,
      builder: (context, snap) {
        final done = snap.connectionState == ConnectionState.done;
        return PageScaffold(
          title: 'Report',
          subtitle: done && snap.hasData
              ? (snap.data!.name ?? widget.studentId)
              : null,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(height: 8),
              if (!done)
                const LoadingState(message: 'Reading the answers')
              else if (snap.hasError)
                _errorFor(snap.error, _reload)
              else
                ..._body(snap.data!),
            ],
          ),
        );
      },
    );
  }

  List<Widget> _body(StudentReport r) {
    return [
      Text(
        '${r.score}',
        style: AppText.displayResult,
      ),
      Text('of ${r.asked}', style: AppText.rowSecondary),
      const SizedBox(height: 14),
      if (r.headline != null)
        Text(r.headline!, style: AppText.sectionTitle),
      if (r.unverified) ...[
        const SizedBox(height: 12),
        const InfoBand(
          text:
              'This wording has not been double-checked yet. The numbers '
              'behind it are still accurate.',
          tone: BandTone.neutral,
          icon: Icons.info_outline,
        ),
      ],
      if (r.crossTopicPattern != null) ...[
        const SizedBox(height: 12),
        InfoBand(text: r.crossTopicPattern!, tone: BandTone.accent),
      ],
      if (r.strengths.isNotEmpty) ...[
        const SectionLabel('Landed well'),
        _conceptCards(r.strengths, good: true),
      ],
      if (r.gaps.isNotEmpty) ...[
        const SectionLabel('Worth another look'),
        _conceptCards(r.gaps, good: false),
      ],
      if (r.byTopic.isNotEmpty) ...[
        const SectionLabel('By topic'),
        Column(
          children: [
            for (final t in r.byTopic) ...[
              FactRow(label: t.topic, value: '${t.correct}/${t.asked}'),
              const SizedBox(height: 6),
            ],
          ],
        ),
      ],
      if (r.nextStep != null) ...[
        const SectionLabel('What to do next'),
        AppCard(child: Text(r.nextStep!, style: AppText.bodySmall)),
      ],
      const SizedBox(height: 18),
      if (r.fromCache) ...[
        InfoBand(
          text: 'Showing the report from when the quiz was finished.',
          tone: BandTone.neutral,
          action: OutlinedAction(
            label: _regenerating ? 'Regenerating…' : 'Regenerate it',
            expand: false,
            onPressed: _regenerating ? null : _regenerate,
          ),
        ),
      ] else
        const InfoBand(
          text: 'Freshly generated just now.',
          tone: BandTone.accent,
        ),
    ];
  }

  Widget _conceptCards(List<ReportConcept> items, {required bool good}) {
    return Column(
      children: [
        for (final c in items) ...[
          AppCard(
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(c.concept, style: AppText.rowTitle),
                      if ((c.evidence ?? '').trim().isNotEmpty) ...[
                        const SizedBox(height: 4),
                        Text(c.evidence!, style: AppText.bodySmall),
                      ],
                    ],
                  ),
                ),
                if (c.verdict != null) ...[
                  const SizedBox(width: 8),
                  TagPill(
                    text: c.verdict!,
                    tone: good ? AppColors.accent : AppColors.grey2,
                    background: good
                        ? AppColors.accentTint
                        : AppColors.neutralBand,
                  ),
                ],
              ],
            ),
          ),
          const SizedBox(height: 8),
        ],
      ],
    );
  }

  static Widget _errorFor(Object? error, VoidCallback onRetry) {
    if (error is ReportNotFoundException) {
      return InfoBand(
        title: 'No report yet',
        text: error.message,
        tone: BandTone.neutral,
      );
    }
    if (error is ReportUnavailableException) {
      return InfoBand(
        title: 'The report could not be generated',
        text: error.message,
        tone: BandTone.neutral,
        action: OutlinedAction(label: 'Try again', onPressed: onRetry),
      );
    }
    return ErrorState(
      message: 'Could not load this report.',
      onRetry: onRetry,
    );
  }
}
